name: unraid-cli

services:

  cli:
    image: devola:5000/unraid-cli:latest
    pull_policy: always
    privileged: true
    group_add:
    - docker
    labels:
      net.unraid.docker.icon: https://icons.iconarchive.com/icons/blackvariant/button-ui-system-apps/256/Terminal-icon.png
    volumes:
    # Docker socket
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    # Unraid mounts
    - type: bind
      source: /mnt
      target: /mnt
    # Unraid system
    - type: bind
      source: /boot
      target: /boot
    # Local volumes
    - type: bind
      source: ./volumes/ssh
      target: /home/unraid-cli/.ssh
